apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetbuddy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budgetbuddy
  template:
    metadata:
      labels:
        app: budgetbuddy
    spec:
      containers:
      - name: budgetbuddy
        image: ECR_URI:latest
        ports:
        - containerPort: 5000
